/* tslint:disable */
/* eslint-disable */
/**
 * Exeq API
 * Remote on-demand browser infrastructure platform API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@exeq.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalServerPublicProfile } from './InternalServerPublicProfile';
import {
    InternalServerPublicProfileFromJSON,
    InternalServerPublicProfileFromJSONTyped,
    InternalServerPublicProfileToJSON,
    InternalServerPublicProfileToJSONTyped,
} from './InternalServerPublicProfile';

/**
 * 
 * @export
 * @interface InternalServerPublicProfileList
 */
export interface InternalServerPublicProfileList {
    /**
     * 
     * @type {Array<InternalServerPublicProfile>}
     * @memberof InternalServerPublicProfileList
     */
    profiles?: Array<InternalServerPublicProfile>;
}

/**
 * Check if a given object implements the InternalServerPublicProfileList interface.
 */
export function instanceOfInternalServerPublicProfileList(value: object): value is InternalServerPublicProfileList {
    return true;
}

export function InternalServerPublicProfileListFromJSON(json: any): InternalServerPublicProfileList {
    return InternalServerPublicProfileListFromJSONTyped(json, false);
}

export function InternalServerPublicProfileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalServerPublicProfileList {
    if (json == null) {
        return json;
    }
    return {
        
        'profiles': json['profiles'] == null ? undefined : ((json['profiles'] as Array<any>).map(InternalServerPublicProfileFromJSON)),
    };
}

export function InternalServerPublicProfileListToJSON(json: any): InternalServerPublicProfileList {
    return InternalServerPublicProfileListToJSONTyped(json, false);
}

export function InternalServerPublicProfileListToJSONTyped(value?: InternalServerPublicProfileList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profiles': value['profiles'] == null ? undefined : ((value['profiles'] as Array<any>).map(InternalServerPublicProfileToJSON)),
    };
}

