/* tslint:disable */
/* eslint-disable */
/**
 * Exeq API
 * Remote on-demand browser infrastructure platform API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@exeq.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalServerErrorResponse
 */
export interface InternalServerErrorResponse {
    /**
     * 
     * @type {number}
     * @memberof InternalServerErrorResponse
     */
    code?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InternalServerErrorResponse
     */
    context?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof InternalServerErrorResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalServerErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the InternalServerErrorResponse interface.
 */
export function instanceOfInternalServerErrorResponse(value: object): value is InternalServerErrorResponse {
    return true;
}

export function InternalServerErrorResponseFromJSON(json: any): InternalServerErrorResponse {
    return InternalServerErrorResponseFromJSONTyped(json, false);
}

export function InternalServerErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalServerErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'context': json['context'] == null ? undefined : json['context'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InternalServerErrorResponseToJSON(json: any): InternalServerErrorResponse {
    return InternalServerErrorResponseToJSONTyped(json, false);
}

export function InternalServerErrorResponseToJSONTyped(value?: InternalServerErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'context': value['context'],
        'error': value['error'],
        'message': value['message'],
    };
}

