/* tslint:disable */
/* eslint-disable */
/**
 * Exeq API
 * Remote on-demand browser infrastructure platform API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@exeq.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalServerPublicSession } from './InternalServerPublicSession';
import {
    InternalServerPublicSessionFromJSON,
    InternalServerPublicSessionFromJSONTyped,
    InternalServerPublicSessionToJSON,
    InternalServerPublicSessionToJSONTyped,
} from './InternalServerPublicSession';

/**
 * 
 * @export
 * @interface InternalServerPublicSessionList
 */
export interface InternalServerPublicSessionList {
    /**
     * 
     * @type {Array<InternalServerPublicSession>}
     * @memberof InternalServerPublicSessionList
     */
    sessions?: Array<InternalServerPublicSession>;
    /**
     * 
     * @type {number}
     * @memberof InternalServerPublicSessionList
     */
    total?: number;
}

/**
 * Check if a given object implements the InternalServerPublicSessionList interface.
 */
export function instanceOfInternalServerPublicSessionList(value: object): value is InternalServerPublicSessionList {
    return true;
}

export function InternalServerPublicSessionListFromJSON(json: any): InternalServerPublicSessionList {
    return InternalServerPublicSessionListFromJSONTyped(json, false);
}

export function InternalServerPublicSessionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalServerPublicSessionList {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(InternalServerPublicSessionFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function InternalServerPublicSessionListToJSON(json: any): InternalServerPublicSessionList {
    return InternalServerPublicSessionListToJSONTyped(json, false);
}

export function InternalServerPublicSessionListToJSONTyped(value?: InternalServerPublicSessionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(InternalServerPublicSessionToJSON)),
        'total': value['total'],
    };
}

